"""empty message

Revision ID: b298fbb27158
Revises: ffdc0a98111c
Create Date: 2022-11-15 19:13:48.778822

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b298fbb27158'
down_revision = 'ffdc0a98111c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('friends',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('friendER', sa.Integer(), nullable=False),
    sa.Column('friendEE', sa.Integer(), nullable=False),
    sa.Column('balance', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['friendER'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('users', sa.Column('firstName', sa.String(length=20), nullable=False))
    op.add_column('users', sa.Column('lastName', sa.String(length=20), nullable=False))
    op.add_column('users', sa.Column('phoneNumber', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('balance', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'balance')
    op.drop_column('users', 'phoneNumber')
    op.drop_column('users', 'lastName')
    op.drop_column('users', 'firstName')
    op.drop_table('friends')
    # ### end Alembic commands ###